services:
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/msf?pool=200&timeout=5
    links:
      - postgres
    ports:
      - 4444:4444
    volumes:
      - ./.msf4:/home/msf/.msf4
    networks:
      - metasploit
    restart: always
 
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - metasploit
    restart: always

volumes:
  postgres_data:
    driver: local
    name: postgres_data

networks:
  metasploit:
    driver: bridge
    name: metasploit
